[package]
name = "ponggers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7.0"
ggez-egui = "0.1.2"
egui = "0.15.0"
glam = "0.20.0"
rand = "0.8.4"